#!/usr/bin/env python3

import subprocess

COMPILER_PATH = "./build/baka"

with open("active_tests") as f:
    for line in f.readlines():
        line = line.strip()

        if(line.startswith("#")):
            continue

        chapter, stage = line.split(",")
        chapter = chapter.strip()
        stage = stage.strip()

        print(f"--chapter {chapter} --stage {stage}")
        subprocess.run(
            ["./test_compiler", "./build/baka", "--chapter", str(chapter), "--stage", str(stage)],
            check = True
        )
